// server.js
// Wrapper script to start the SvelteKit app with a default port of 3001
// This solves the issue where port 3000 is occupied on shared hosting (e.g. aaPanel)

// Set default port to 3001 if not already set via environment variable
process.env.PORT = process.env.PORT || '3001';

console.log(`Starting server on port ${process.env.PORT}...`);

// Import the SvelteKit build (generated by adapter-node)
// Note: This requires 'npm run build' to have been run first
await import('./build/index.js');
